# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Basic variables
#==========================================================================================
title: Verification Plugin Documentation
description: >- # this means to ignore newlines until "baseurl:"
  A Bootstrap 4 start up project for Jekyll and Github Pages
#baseurl: "/en" # the subpath of your site, e.g. /blog
url: "https://afp-medialab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurlguide: /verificationplugin/guide

repository: "AFP-Medialab/AFP-Medialab.github.io"




# Build settings
#==========================================================================================
plugins:
  - jekyll-feed
  - jekyll-sitemap





# A list of the pages to display in the navigation bar
#==========================================================================================
header_pages:





# Exclude from processing.
#==========================================================================================
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh


# Translations
#==========================================================================================
t:
  en:
    home:  "Home"

    video: "Video"
    tools-analysis:  "Video Analysis"
    tools-keyframes:  "Keyframes"
    tools-thumbnails:  "Thumbnails"
    tools-videometadata:  "Metadata"
    tools-deepfake:  "Deepfake"
    tools-poiforensics:  "POI Forensics"

    image: "Image"
    tools-metadata:  "Metadata"
    tools-forensic:  "Forensic"
    tools-magnifier:  "Magnifier"
    tools-ocr:  "OCR"
    tools-gif:  "CheckGIF"
    tools-syntheticimagedetection:  "Synthetic Image Detection"
    tools-geolocation:  "Geolocalizer"
    tools-c2pa:  "Provenance (C2PA)"

    audio: "Audio"
    tools-hiya:  "Hiya"

    search: "Search"
    tools-twitter:  "X. Search"
    tools-semanticsearch:  "Fact Check Semantic Search"
    tools-factchecksearch:  "Factcheck Search"
    tools-xnetwork:  "XNetwork"
    tools-mgt:  "Machine Generated Text"

    data: "Data analysis"
    tools-twitterSNA:  "Twitter SNA"
    tools-csvsna:  "CSV Analysis"
    tools-sna:  "Social Network Analysis"
    tools-disinfodeck:  "Disinformation Monitoring Dashboard"

    other: "Other tools"
    tools-ffmpegtoolkit:  "FFMPEG Toolkit"
    tools-archive:  "Archiving"
    tools-chatbot:  "Chatbot"


  es:
    home:  "Inicio"

    video: "Video"
    tools-analysis:  "Análisis de vídeo"
    tools-keyframes:  "Keyframes"
    tools-thumbnails:  "Thumbnails"
    tools-videometadata:  "Metadata"
    tools-deepfake:  "Deepfake"
    tools-poiforensics:  "POI Forensics"

    image: "Image"
    tools-metadata:  "Metadata"
    tools-forensic:  "Forensic"
    tools-magnifier:  "Magnifier"
    tools-ocr:  "OCR"
    tools-gif:  "CheckGIF"
    tools-syntheticimagedetection:  "Detección de imagen sintética"
    tools-geolocation:  "Geolocalizador"
    tools-c2pa:  "Procedencia (C2PA)"

    audio: "Audio"
    tools-hiya:  "Hiya"

    search: "Search"
    tools-twitter:  "X. Search"
    tools-semanticsearch:  "Búsqueda semántica"
    tools-factchecksearch:  "Búsqueda Factcheck"
    tools-xnetwork:  "XNetwork"
    tools-mgt:  "Texto generado por máquina"

    data: "Data analysis"
    tools-twitterSNA:  "Twitter SNA"
    tools-csvsna:  "Análisis CSV"
    tools-sna:  "Análisis de redes sociales"
    tools-disinfodeck:  "Panel de monitoreo de desinformación"

    other: "Other tools"
    tools-ffmpegtoolkit:  "FFMPEG Toolkit"
    tools-archive:  "Archiving"
    tools-chatbot:  "Chatbot"

  fr:
    home:  "Accueil"

    video: "Vidéo"
    tools-analysis:  "Analyse vidéo"
    tools-keyframes:  "Keyframes"
    tools-thumbnails:  "Miniatures"
    tools-videometadata:  "Métadonnées"
    tools-deepfake:  "Deepfake"
    tools-poiforensics:  "POI Forensics"

    image: "Image"
    tools-metadata:  "Métadonnées"
    tools-forensic:  "Forensic"
    tools-magnifier:  "Loupe"
    tools-ocr:  "OCR"
    tools-gif:  "CheckGIF"
    tools-syntheticimagedetection:  "Détection d'image synthétique"
    tools-geolocation:  "Géolocalisateur"
    tools-c2pa:  "Provenance (C2PA)"

    audio: "Audio"
    tools-hiya:  "Hiya"

    search: "Recherche"
    tools-twitter:  "Recherche X."
    tools-semanticsearch:  "Recherche sémantique Factcheck"
    tools-factchecksearch:  "Recherche Factcheck"
    tools-xnetwork:  "XNetwork"
    tools-mgt:  "Texte généré par machine"

    data: "Analyse de données"
    tools-twitterSNA:  "Twitter SNA"
    tools-csvsna:  "Analyse CSV"
    tools-sna:  "Analyse de réseau social"
    tools-disinfodeck:  "Tableau de bord de surveillance de la désinformation"

    other: "Autres outils"
    tools-ffmpegtoolkit:  "FFMPEG Toolkit"
    tools-archive:  "Archivage"
    tools-chatbot:  "Chatbot"

  gr:
    home:  "Σπίτι"

    video: "Βίντεο"
    tools-analysis:  "Ανάλυση βίντεο"
    tools-keyframes:  "Keyframes"
    tools-thumbnails:  "Thumbnails"
    tools-videometadata:  "Μεταδεδομένα"
    tools-deepfake:  "Deepfake"
    tools-poiforensics:  "POI Forensics"

    image: "Εικόνα"
    tools-metadata:  "Μεταδεδομένα"
    tools-forensic:  "Forensic"
    tools-magnifier:  "Μεγεθυντής"
    tools-ocr:  "OCR"
    tools-gif:  "CheckGIF"
    tools-syntheticimagedetection:  "Ανίχνευση συνθετικής εικόνας"
    tools-geolocation:  "Γεωεντοπιστής"
    tools-c2pa:  "Προέλευση (C2PA)"

    audio: "Ήχος"
    tools-hiya:  "Hiya"

    search: "Αναζήτηση"
    tools-twitter:  "Αναζήτηση X."
    tools-semanticsearch:  "Σημασιολογική αναζήτηση Factcheck"
    tools-factchecksearch:  "Αναζήτηση Factcheck"
    tools-xnetwork:  "XNetwork"
    tools-mgt:  "Κείμενο παραγόμενο από μηχανή"

    data: "Ανάλυση δεδομένων"
    tools-twitterSNA:  "Twitter SNA"
    tools-csvsna:  "Ανάλυση CSV"
    tools-sna:  "Ανάλυση κοινωνικού δικτύου"
    tools-disinfodeck:  "Πίνακας παρακολούθησης παραπληροφόρησης"

    other: "Άλλα εργαλεία"
    tools-ffmpegtoolkit:  "FFMPEG Toolkit"
    tools-archive:  "Αρχειοθέτηση"
    tools-chatbot:  "Chatbot"